spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-vl-plus
          temperature: 0.5
server:
  port: 8085
