server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/**
        - id: volunteerActivity-service
          uri: lb://volunteerActivity-service
          predicates:
            - Path=/volunteerActivity/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/shopping/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
      httpclient:
        headers:
          allow-forwards: true