spring:
  application:
    name: shopping-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    url: jdbc:mysql://localhost:3306/animal_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "041115"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    map-underscore-to-camel-case: true

server:
  port: 8083
